### ISSUE TITLE
选择用户安装应用的时候提示 "versionName must not be null"

### ISSUE THREAD

**Issue by BCsl** [jingcai-wei/xposed-load#1]
`    java.lang.IllegalStateException: versionName must not be null
        at com.sky.xposed.load.data.local.PluginManager.newAppInfo(PluginManager.kt:207)
        at com.sky.xposed.load.data.local.PluginManager.loadLocalApps(PluginManager.kt:106)
        at com.sky.xposed.load.data.local.PluginManager$loadApps$1.invoke(PluginManager.kt:80)
        at com.sky.xposed.load.data.local.PluginManager$loadApps$1.invoke(PluginManager.kt:40)
        at com.sky.xposed.load.data.local.PluginManager$onUnsafeCreate$1.call(PluginManager.kt:285)
        at com.sky.xposed.load.data.local.PluginManager$onUnsafeCreate$1.call(PluginManager.kt:282)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by BCsl** [comment]
发现安装了一个 apk 没有 versionName 有关

**Comment by jingcai-wei** [comment]
嗯，我到时修复下.
